# Generated by Django 5.0 on 2023-12-06 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_blog_owner_alter_blog_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="created_at",
            new_name="date_added",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="date_added",
        ),
    ]
